import jsPDF from "jspdf";
import type { Language, Message } from "../chat-types/chat";

export async function exportConversationPdf(
  messages: Message[],
  language: Language,
) {
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  const margin = 15;
  const contentWidth = pageWidth - margin * 2;

  let y = 20;

  // ─────────────────────────────
  // HEADER
  // ─────────────────────────────

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text("Crescent Admission Assistant", margin, y);

  y += 8;

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(10);
  pdf.text(`Language: ${language.toUpperCase()}`, margin, y);

  y += 6;

  pdf.text(
    `Date: ${new Date().toLocaleString()}`,
    margin,
    y,
  );

  y += 8;

  pdf.line(
    margin,
    y,
    pageWidth - margin,
    y,
  );

  y += 10;

  // ─────────────────────────────
  // CONVERSATION
  // ─────────────────────────────

  if (!messages || messages.length === 0) {
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);
    pdf.text("No conversation available.", margin, y);
  } else {
    messages.forEach((message) => {
      const sender =
        message.sender === "user"
          ? "You"
          : "Crescent Admission Assistant";

      const text = message.text || "";

      if (!text.trim()) {
        return;
      }

      // Check page space before sender
      if (y > pageHeight - 35) {
        pdf.addPage();
        y = 20;
      }

      // Sender
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(11);
      pdf.text(sender, margin, y);

      y += 6;

      // Message text
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(10);

      const lines = pdf.splitTextToSize(
        text,
        contentWidth,
      );

      lines.forEach((line: string) => {
        if (y > pageHeight - 20) {
          pdf.addPage();
          y = 20;
        }

        pdf.text(line, margin, y);
        y += 5;
      });

      y += 7;
    });
  }

  // ─────────────────────────────
  // FOOTER
  // ─────────────────────────────

  if (y > pageHeight - 15) {
    pdf.addPage();
  }

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(8);

  pdf.text(
    "Generated by Crescent Admission Assistant",
    margin,
    pageHeight - 10,
  );

  // ─────────────────────────────
  // DOWNLOAD
  // ─────────────────────────────

  const date = new Date()
    .toISOString()
    .split("T")[0];

  pdf.save(`crescent-chat-${date}.pdf`);
}